name: "Trigger"

on:
  # Enable 'Run workflow' button.
  workflow_dispatch:

jobs:
  trigger:
    name: "Trigger target build"
    runs-on: ubuntu-latest

    steps:
      - name: Trigger 'trigger-target' build
        with:
          PAT: ${{ secrets.TRIGGER_PAT }}
        run: |
            repo_name=trigger-target
            event_type="trigger-workflow"
            curl -qs \
              --fail-with-body \
              -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PAT }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/$GITHUB_REPOSITORY_OWNER/$repo_name/dispatches \
              -d "{\"event_type\": \"$event_type\"}"
